// <auto-generated />
using Mango.Services.ProductAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Smart Phone",
                            Description = "IPhone X",
                            ImageUrl = "https://fakeimg.pl/440x230/282828/eae0d0/?retina=1&text=Supports%20emojis!%20%F0%9F%98%8B",
                            Name = "IPhone X",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Smart Phone",
                            Description = "Samsung Galaxy S10",
                            ImageUrl = "https://fakeimg.pl/440x230/282828/eae0d0/?retina=1&text=Supports%20emojis!%20%F0%9F%98%8B",
                            Name = "Samsung Galaxy S10",
                            Price = 900m
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Smart Phone",
                            Description = "Google Pixel 3",
                            ImageUrl = "https://fakeimg.pl/440x230/282828/eae0d0/?retina=1&text=Supports%20emojis!%20%F0%9F%98%8B",
                            Name = "Google Pixel 3",
                            Price = 800m
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Smart Phone",
                            Description = "OnePlus 6T",
                            ImageUrl = "https://fakeimg.pl/440x230/282828/eae0d0/?retina=1&text=Supports%20emojis!%20%F0%9F%98%8B",
                            Name = "OnePlus 6T",
                            Price = 700m
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Smart Phone",
                            Description = "Nokia 9 PureView",
                            ImageUrl = "https://fakeimg.pl/440x230/282828/eae0d0/?retina=1&text=Supports%20emojis!%20%F0%9F%98%8B",
                            Name = "Nokia 9 PureView",
                            Price = 600m
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Smart Phone",
                            Description = "Sony Xperia 1",
                            ImageUrl = "https://fakeimg.pl/440x230/282828/eae0d0/?retina=1&text=Supports%20emojis!%20%F0%9F%98%8B",
                            Name = "Sony Xperia 1",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Smart Phone",
                            Description = "LG G8 ThinQ",
                            ImageUrl = "https://fakeimg.pl/440x230/282828/eae0d0/?retina=1&text=Supports%20emojis!%20%F0%9F%98%8B",
                            Name = "LG G8 ThinQ",
                            Price = 800m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
